aedocw/epub2tts

.gitignore
README.md

Instructions were bad and asked you to create a venv in root of project. Updated to suggest creating it in hidden directory .venv, and added that to .gitignore

2 instructions dont cd back to project root

---

epub2tts.py

This seems to work. Removes links in their entirety, so text like:
This is the text <a href="footnote10.html">[10]</a>
becomes:
This is the text.
It may have undesired side effect of removing copy that you want, but so far none of the epubs I've tested with have had anything other than footnotes or table of content pages that were links.

Skip the links

---

epub2tts.py
setup.py

This adds "--model" option (still need to update readme and internal help to reflect this).
For instance to use the vits spanish model:
epub2tts my-book.epub --model tts_models/es/css10/vits

added --model option

---

epub2tts.py
setup.py

This should have stayed in here in the first place. When reading from a txt file (rather than epub), it is unable to detect chapters, so it breaks the text up every 50000 characters instead. Probably will make that 30k characters in the future.

bring back breaking up text into chunks

---

epub2tts.py
setup.py

This branch is wrongly named, but originally I thought I would just use mp3 files for temp, unfortunately that introduced audio artifacts (possibly could have worked on ffmpeg parameters to tune it better, but...) Converting the intermediate wav files to flac though is clean and results in files less than half the original size.

Use FLAC for temp files

---

epub2tts.py
setup.py

Listening to books with no announcement of the next chapter makes it all just flow together. Adding a longer gap (3 seconds) should be enough to give a clear sense that a new chapter is starting.

Add 3 seconds of silence at the end of chapters

---

README.md
epub2tts.py
setup.py

This allows the user to disable the step that uses whisper to make a transcript of the output, and compares it to the original text, by adding:
`--minratio 0`
when calling epub2tts

Optional whisper

---

epub2tts.py
setup.py

This skips doing the whisper transcript comparison if using default VITS model.

No whisper sometimes

---

README.md
epub2tts.py
setup.py

This adds a function to check if a package is installed, uses that function to check if deepspeed is installed, and then uses deepspeed with XTTS if it is available.

Use deepspeed

---

epub2tts.py
setup.py

Makes OpenAI work again by recognizing file coming back is an mp3, but ffmpeg was expecting it to be a wave. Also force speaker name to lower-case (which OpenAI expects). AND finally, skip whisper transcript comparison if we're using OpenAI.

Fixing issues that broke openAI

---

README.md

i was looking for samples of all the xtts voices while researching for potetial backends and could not found it, so I generated them and put them in a repo
you python script does the same but only after already setting everything up...maybe its useful to listen to examples before investing the time

add a link to repository with already generated xtts voice samples

---

epub2tts.py
setup.py

If the list of sentences to speak has an empty item in it, TTS will crash when asked to speak that. This adds a check for length of sentence to speak, and skips if the length is 0.

dont try to send an empty sentence to TTS

---

epub2tts.py
setup.py

If the user adds "--export" or "--export txt", the epub is exported to a text file with the same name as the epub. This also supports "--start" and "--end" options if the user wants to export only a specific section.

Added --export txt option

---

epub2tts.py

This removes the intermediate step of transcoding wav files to FLAC files, and uses ffmpeg from the shell to concat the chapter files at the end. This is faster, and should resolve issues with long audiobooks.

Ffmpeg concat

---

epub2tts.py
setup.py

This fixes an issue where if a filename had a single quote in it, ffmpeg would choke. This properly escapes that single quote for ffmpeg's concat file list.

escape single quote for ffmpeg concat list

---

epub2tts.py
setup.py

Any "#" in a text file would trigger a chapter break, but that would not match expected chapters so an index out of range would be triggered. This fixes that, along with the "say parts" section so that it will properly say the chapter name.

Fixed detection of chapter breaks and section names

---

epub2tts.py
setup.py

This branch was poorly named, main thing I added here was some better debugging (it now outputs one line for each chunk sent to XTTS into a text file). This was to help me see better what text substitutions were happening, like replacement of ". . .". I also found that adding a line break after chapter names when using "--sayparts" made a difference. It was reliably pronouncing the period except with gibberish. Adding the line break made that go away.

better debugging

---

README.md
epub2tts.py
setup.py

Ensuring a 3 second pause between each chapter/part was only being honored for epub files. I removed that conditional so it also happens for text based files.

Remove condition to add 2 second silence only for epub

---

README.md
epub2tts.py
setup.py

This PR takes work suggested in two different issues (https://github.com/aedocw/epub2tts/issues/153 and https://github.com/aedocw/epub2tts/issues/208), and adds a 0.6sec pause after each sentence. This will also limit the length of text sent to TTS which will likely eliminate the "character limit" error sometimes seen.
This does seem to make a really nice improvement in the overall quality.

Uniform pause after sentence

---

README.md
epub2tts.py
setup.py

The default behavior is to replace or remove characters that are not pronounced or part of a word, as it can cause XTTS to speak gibberish.
When `--skip-cleanup` is specified, epub2tts will NOT replace these characters with " " or ",".

Add --skip-cleanup option

---

epub2tts.py
setup.py

NCX files is the epub file that contain the content index.
This change makes it so that epub2tts can separate the text based on sections as they are specified in the ncx file.
Instead of simply assuming that each file is a separate chapter.

Add suport for ncx files

---

epub2tts.py
setup.py

If using text file as source, the first line of the copy must be a chapter marker like `# Intro` or something. Bail if that is missing.

Bail if first chapter marker is missing

---

epub2tts.py

Fix for the issue seen in issue: https://github.com/aedocw/epub2tts/issues/280

Stop cover image file errors from crashing the script

---

epub2tts.py
setup.py

Would be nice to be able to view the text sentence by sentence as it is spoken.
One way to save such data is a .srt file.
This PR intends to add .srt file support to epub2tts.
Things to do:

Adding .srt support
