- Dockerfile
- README.md
- epub2tts.py
This adds a Dockerfile and updates instructions accordingly.
> Dockerize it

- epub2tts.py
Added code to check for a second parameter and see if it matches one of the valid options for a speaker for this voice model. Uses this variable 'speaker_used' to pass to the tts function. Adds speaker used to output mp3 filename.
> Add option to select a different speaker

- README.md
- epub2tts.py
- setup.py
This adds "--chapters" option, which changes output to an m4b with chapter start/end data embedded.
Without adding "--chapters" to command line, it just creates and mp3 file as always.
> Add option to output as m4b audiobook file with chapters

- README.md
- epub2tts.py
- setup.py
Merging latest code to trigger a docker build
> Make m4b with chapters default

- epub2tts.py
- setup.py
This was originally going to be all about more efficiently breaking up long chapters, but in the process of testing I learned it wasn't long chapters that caused problems but long sentences. I logged a bug and at least have some ideas on how to address, but since it's a problem with an external library (pySBD), probably not a lot I can do about it.
THEN this branch became about just making some minor cleanup really.
> Are we breaking up

- epub2tts.py
- setup.py
Still amateur hour coding here, but this cleans things up a tiny bit at least
> Moving some things to funtions to help eventual move to classes

- epub2tts.py
- setup.py
> Dont start over

- epub2tts.py
Added the method for using cuda in the audio elaboration.
Take a look.
It is working for me.
> Add CUDA support with .to_device() method like TTS

- README.md
- epub2tts.py
- requirements.txt
- setup.py
This was a pretty clunky way to wedge this in here, but it works at least. Gives me a lot of ideas at least for how to refactor all of this so it's much cleaner, and can incorporate more TTS engines as well.
> 60 add openai tts option

- README.md
- epub2tts.py
- requirements.txt
- setup.py
> Trigger docker image build

- README.md
- epub2tts.py
- setup.py
This adds the ability to use the Coqui XTTS model which is based on Tortoise but highly optimized. It allows you to supply a short sample voice for cloning, and then does an amazing job of copying that voice. GPU absolutely required, and even then it's pretty slow (but worth it!)
> Enable Coqui XTTS

- epub2tts.py
- requirements.txt
- setup.py
This uses whisper to make a transcript of each audio output chunk, and does a fuzzy comparison of the transcript to the original text. If it's below a threshold, it will try to encode again.
> Whatdyousay

- epub2tts.py
- setup.py
This doesn't fix the related issue but does improve how voice samples are referenced.
> Fix paths for voice samples

- epub2tts.py
- requirements.txt
- setup.py
Ooops, this branch was supposed to be called use-nltk. It replaces pysbd with NLTK (natural language tool kit) which seems to do a much better job at sentence segmentation.
> Replace pysbd with nltk for better sentence segmentation

- README.md
- epub2tts.py
- setup.py
- utils/README.md
- utils/copy_model.py
- utils/install_reqs.sh
- utils/run_gradio.sh
Adds ability to specify a fine-tuned XTTS v2 model with "--model" option.
> Xtts model

- epub2tts.py
- setup.py
Responding to linked bug, it was not properly catching the requirement for something to be supplied with "--xtts".
> Handle xtts params better

- epub2tts.py
- setup.py
Initial attempt to put 3 seconds of silence between each chapter/part was wrong, this works properly now.
> More quiet

- epub2tts.py
as for what reported by [danielw97] https://github.com/aedocw/epub2tts/issues/116
> Updated VRAM lower limit

- README.md
- epub2tts.py
- setup.py
- utils/generate-speaker-samples.py
This merges new functionality allowing you to use coqui speakers (formerly Coqui Studio voices). See README for usage.
> Coqui speakers

- epub2tts.py
- setup.py
- utils/tests.sh
Merge to allow use of coqui speakers broke some other stuff, and I merged it before fully testing. This addresses the things that broke, and also includes a script (mainly for my use) that tests the most common usage.
> Fixes for things I just broke

- epub2tts.py
- setup.py
This adds an option `--sayparts` which will insert "Part n" at the start of each section (i.e. "Part 1"). I wanted to do this because some books don't have much indication that you're starting a new chapter.
> Which part

- epub2tts.py
- setup.py
This takes the list of sentences that will be sent to TTS and removes any that do NOT have at least one letter or number in them. When TTS is asked to speak sentences that just contain things like "..." or even just one double-quote, it sounds like gibberish. Will be nice to try to catch and remove those.
> Dont say that

- epub2tts.py
- setup.py
As noted in linked issue, this change uses streaming approach for XTTS with Coqui voices, which can utilize deepspeed.
> Streaming coqui voices

- README.md
- epub2tts.py
- setup.py
This adds functionality when using text files as your source, and will treat any line beginning with "# " as a new chapter/part/section. This is coupled with "--export txt" functionality which creates a text file from epub, with chapter breaks.
> Chapter breaks in text

- .github/workflows/docker-publish.yml
- Dockerfile.cuda12
This adds a dockerfile for a cuda 12 container
> Add cuda container

- epub2tts.py
- setup.py
This should trigger a container build
> Trigger docker build

- README.md
- epub2tts.py
- requirements.txt
- setup.py
This adds the "--cover" option to include cover art with your audiobook m4b.
> 191 add cover art

- README.md
This is a major update to the README, improving instructions and the layout.
> More better docs

- epub2tts.py
Hello @aedocw 
It is also the first step for later addition, but I will explain why below. I can open a discussion later if you prefer.
- I first export my epub as txt like it is advised
- I prepare my first chapter and I only export this chapter, I could use --start and --end, but I often only make a `chapter1.txt`
- I make the "chapter" audiobook and I listen to it. Doing it like that lets me replace words that could be wrong, or also change the voice if I don't like it without losing too much time because I use my CPU so using xtts can be very slow
The idea of the pr is to be able to keep an "untouched" audio file and so later to be able to concat them all if I want to keep it. I was thinking to maybe make a new script to concat multiple input files and also to convert them in m4b. It …
> Add possibility to save the output file in wav or flac

- epub2tts.py
- setup.py
Added try / except to export() function.
> Add try / except block

- epub2tts.py
- setup.py
Added functionality in the export() to automatically get the book's cover image and save it as the name of the book + .png.
> Added functionality in the export() automatically get the cover image of the book

- epub2tts.py
Refactoring the text 2 audio part of the code in to separate classes for each engine.
This will clean up the code allot and make implementing multiprocessing very easy and clean.
The idea is to have a main class (Text2WaveFile) that all backend engines inherit from.
This way most of the code does not need to know what backend engine is being used.
> refactoring code to prepare for multiprocessing

- epub2tts.py
PR that adds parallel execution.
Where each chapter gets it own process.
Just did a 7 hour audiobook in 9 minutes on my MacBook using 16 threads.
Using the new --threads argument
> Multiprocessing
